name: sync-faq
on:
  issue_comment:
    types: [created]

jobs:
  sync-faq:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title,'FAQ:') && startsWith(github.event.comment.body,'/faq')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
